/* import { ITattooImage } from "../types/types"
import { images } from "./images"

export const data: ITattooImage[] = [
    { id: 26, img: images.ta26, artist: "Sam", style: "Classic", color: "Color" },
    { id: 20, img: images.ta20, artist: "Alex", style: "Realism", color: "Color" },
    { id: 1, img: images.ta1, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 16, img: images.ta16, artist: "Sam", style: "Classic", color: "Color" },
    { id: 2, img: images.ta2, artist: "Sam", style: "Classic", color: "Color" },
    { id: 3, img: images.ta3, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 27, img: images.ta27, artist: "Alex", style: "Classic", color: "Color" },
    { id: 4, img: images.ta4, artist: "Alex", style: "Classic", color: "Color" },
    { id: 5, img: images.ta5, artist: "Sam", style: "Classic", color: "Color" },
    { id: 6, img: images.ta6, artist: "Sam", style: "NewSchool", color: "Color" },
    { id: 7, img: images.ta7, artist: "Sam", style: "Classic", color: "Color" },
    { id: 8, img: images.ta8, artist: "Sam", style: "NewSchool", color: "Color" },
    { id: 9, img: images.ta9, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 10, img: images.ta10, artist: "Sam", style: "Realism", color: "Color" },
    { id: 11, img: images.ta11, artist: "Sam", style: "Classic", color: "Color" },
    { id: 12, img: images.ta12, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 13, img: images.ta13, artist: "Alex", style: "Classic", color: "Color" },
    { id: 14, img: images.ta14, artist: "Sam", style: "Classic", color: "Color" },
    { id: 15, img: images.ta15, artist: "Alex", style: "Classic", color: "Color" },
    { id: 17, img: images.ta17, artist: "Sam", style: "Classic", color: "Color" },
    { id: 18, img: images.ta18, artist: "John", style: "NewSchool", color: "Color" },
    { id: 19, img: images.ta19, artist: "Alex", style: "NewSchool", color: "Black" },
    { id: 21, img: images.ta21, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 22, img: images.ta22, artist: "Sam", style: "NewSchool", color: "Color" },
    { id: 23, img: images.ta23, artist: "Alex", style: "Classic", color: "Color" },
    { id: 24, img: images.ta24, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 25, img: images.ta25, artist: "Sam", style: "Classic", color: "Color" },
    { id: 1126, img: images.ta26, artist: "Sam", style: "NewSchool", color: "Color" },
    { id: 1120, img: images.ta20, artist: "Sam", style: "Classic", color: "Color" },
    { id: 111, img: images.ta1, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 1116, img: images.ta16, artist: "Sam", style: "Classic", color: "Color" },
    { id: 112, img: images.ta2, artist: "John", style: "NewSchool", color: "Black" },
    { id: 113, img: images.ta3, artist: "Alex", style: "Classic", color: "Color" },
    { id: 1127, img: images.ta27, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 114, img: images.ta4, artist: "Alex", style: "Classic", color: "Color" },
    { id: 115, img: images.ta5, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 116, img: images.ta6, artist: "Sam", style: "Classic", color: "Color" },
    { id: 117, img: images.ta7, artist: "Alex", style: "Classic", color: "Color" },
    { id: 118, img: images.ta8, artist: "Sam", style: "NewSchool", color: "Color" },
    { id: 119, img: images.ta9, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 1110, img: images.ta10, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 1111, img: images.ta11, artist: "Alex", style: "Realism", color: "Color" },
    { id: 1112, img: images.ta12, artist: "Sam", style: "NewSchool", color: "Color" },
    { id: 1113, img: images.ta13, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 1114, img: images.ta14, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 1115, img: images.ta15, artist: "Alex", style: "Classic", color: "Black" },
    { id: 1117, img: images.ta17, artist: "John", style: "NewSchool", color: "Color" },
    { id: 1118, img: images.ta18, artist: "Alex", style: "Classic", color: "Color" },
    { id: 1119, img: images.ta19, artist: "Alex", style: "NewSchool", color: "Color" },
    { id: 1121, img: images.ta21, artist: "Sam", style: "Classic", color: "Color" },
    { id: 1122, img: images.ta22, artist: "Alex", style: "Classic", color: "Color" },
    { id: 1123, img: images.ta23, artist: "Alex", style: "Classic", color: "Color" },
    { id: 1124, img: images.ta24, artist: "Sam", style: "NewSchool", color: "Color" },
    { id: 1125, img: images.ta25, artist: "Alex", style: "NewSchool", color: "Color" },
]
 */
